auto: true
highlighter: rouge
server: true
markdown: kramdown
permalink: /:categories/:title/
email: info@teachosm.org
columnist:
  paths:
  - _posts
baseurl: ''
prose:
  rooturl: '_posts'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
translations:
  en:
    tagline: "Teach OpenStreetMap Step by Step"
    contribute: "Help improve our guides"
    trainingspan: "Are you a workshop organizer?"
    training: "Check out training material for this guide (in English)"
    feedbackspan: "Was this chapter helpful?"
    feedback: "Let us know and help us improve the guides!" 
  de:
    tagline: "Lerne OpenStreetMap Schritt für Schritt kennen"
    contribute: "Hilf mit, unsere Anleitungen zu verbessern"
    trainingspan: "Veranstaltest du Workshops?"
    training: "Siehr dir unsere Unterlagen für diesen Kurs an (in Englisch)"
    feedbackspan: "War dieses Kapitel hilfreich?"
    feedback: "Sende uns Feedback und verbessere die Anleitungen!"
    getstarted: "weiter zum nächsten Kapitel"
